name: hello

on:
  push:
    branches: [main]

jobs:
  greet:
    runs-on: ubuntu-latest   # Specify the environment here
    steps:
      - name: say Hello to users
        run: echo "Hello Dosto"

      - name: say hello to user name
        run: echo "Hello $USER"
