name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  Code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        run: echo "code is been cloned"
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: buikd docker container
        run: echo "build successfully" 
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Test are doing
        run: echo "test has Done"
  Deploye:
    runs-on: ubuntu-latest
    steps:
      - name:  Deploye Steps
        run: echo "deploye is done "
